export  default {
    //房间
    selRoom:[
        {
            key:1,
            value:'1室'
        },{
            key:2,
            value:'2室'
        }
    ],
    //客厅
    selSaloon:[
        {
            key:1,
            value:'1厅'
        },{
            key:2,
            value:'2厅'
        }
    ],
    //客厅
    selKitchen:[
        {
            key:1,
            value:'1厨'
        },{
            key:2,
            value:'2厨'
        }
    ],
    //卫生间
    selToilet:[
        {
            key:1,
            value:'1卫'
        },{
            key:2,
            value:'2卫'
        }
    ],
    //装修档次
    selGrade:[
        {
            key:5,
            value:'高档'
        },{
            key:4,
            value:'中高档'
        }
    ]
}